# Generated by Django 2.2 on 2019-04-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('Take Pet for a Walk', 'Take Pet for a Walk'), ('Ignore', 'Ignore'), ('Go to Petstore', 'Go to Petstore')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('Dog Food', 'Dog Food'), ('Chocolate', 'Chocolate'), ("Today's Lunch", "Today's Lunch")], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('breed', models.CharField(max_length=120)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('states', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.PetState')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PetDescription',
        ),
    ]
