# Generated by Django 2.2 on 2019-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190416_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='states',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Mix-breed', max_length=120),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=4),
        ),
    ]
