# Generated by Django 2.2 on 2019-04-24 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190421_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstate',
            name='fun',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
